### ISSUE TITLE
redisearch的全文检索感觉不太好用，分词效果不好就搜索不出来，有没有什么好的方案？

### ISSUE THREAD

**Issue by ifakeu** [wayn111/newbee-mall#3]
![图片](https://user-images.githubusercontent.com/6261780/174198713-8b2b2243-ad6a-456c-a070-adcbb696a5ec.png)
比如“全网通”、“双卡双待”，如果不在分词结果里面，搜不出来
![图片](https://user-images.githubusercontent.com/6261780/174198882-cc233d98-cd6d-4ed6-90d7-6ba6966a4bc5.png)

**Comment by wayn111** [comment]
搜索语句后加上 language
FT.SEARCH idx:goods '双卡' language chinese

**Comment by ifakeu** [comment]
> 搜索语句后加上 language FT.SEARCH idx:goods '双卡' language chinese

创建索引的时候指定了language chinese了，一样搜不出，因为friso的分词结果没有“双卡”

**Comment by wayn111** [comment]
有 双 这个分词，搜索的时候不指定language会按英文搜

**Comment by wayn111** [comment]
项目里你更新到最新代码，搜双卡双待能搜出来东西的，我提交了代码
