### ISSUE TITLE
导入SQL文件出现错误

### ISSUE THREAD

**Issue by puchihhh** [wayn111/newbee-mall#4]
用newbee_mall_db_包含秒杀and优惠卷.sql在Navicat运行只导出"tb_newbee_mall_admin_user"和"tb_newbee_mall_carousel"两张表, 
选择出错时停止运行时如图
![image](https://user-images.githubusercontent.com/55620106/190903137-8c715fc9-ed28-4390-8eac-49f73250d172.png)

**Comment by wayn111** [comment]
你是导入sql脚本报错？Mysql最低得5.7+版本

**Comment by puchihhh** [comment]
确实版本低了, 但升级后导入时还是报错. 又按照网上的方法勾选"在每个运行中运行多个查询"还是报错.
如果选出错就停止会卡在这里
![image](https://user-images.githubusercontent.com/55620106/190954460-552d3afd-5472-4a35-bb37-6c3bd4dd069d.png)
如果选出错也继续还是有17处错误
![image](https://user-images.githubusercontent.com/55620106/190954650-851dcb06-6aad-4112-9773-1f4f25675ae5.png)
能导出的表有10张
![image](https://user-images.githubusercontent.com/55620106/190954727-3adb24df-fa00-4c0c-88b5-7cf9b25b8c34.png)

**Comment by wayn111** [comment]
![image](https://user-images.githubusercontent.com/34181171/190955150-81e4575c-77b5-476a-b031-9cc881d9fb2b.png)
你是mysql5.7+吗，导入成功后有13张表
![image](https://user-images.githubusercontent.com/34181171/190955239-5f597d95-04b6-46cb-b438-07cc3730dd76.png)

**Comment by wayn111** [comment]
可以直接把报错的sql语句再navicat里执行，看下你是为什么报错

**Comment by puchihhh** [comment]
搞好了, 还是mysql版本不兼容的问题, 把所有的utf8mb4_0900_ai_ci替换为utf8_general_ci，以及所有的utf8mb4替换为utf8再执行就可以了
